### ISSUE TITLE
MacOS Download Becomes a Document File

### ISSUE THREAD

**Issue by JustaSqu1d** [UhhhAaron/SaladBind#8]
## How to reproduce
Click download and double click to open. After confirming you want to open, it will open from text edit.

**Comment by JustaSqu1d** [comment]
After following README.md. It stays as a Document file. It may have to do with the fact that my computer uses the M1 chip.

**Comment by aj-swartz** [comment]
Seems like somewhere in either the downloading or uploading process it gets seen as a document. I put the script in an archive which seems to protect it from whatever formatting trickery the script goes through. Updated the release page to have the macOS script download as an archive.

You may or may not need NodeJS to run it. If you do, download is here: https://nodejs.org/en/download/
Updated release page: https://github.com/UhhhAaron/SaladBind/releases/tag/final-release
